import * as user from './user';
import * as users from './users';
import * as events from './events';
import * as navigation from './navigation';
import * as interests from './interests';
import * as invites from './invites';
import * as requests from './requests';
import * as search from './search';
import * as notifications from './notifications';
import * as payments from './payments';
import * as network from './network';
import * as startup from './startup';

export const userActions = user;
export const usersActions = users;
export const eventActions = events;
export const navigationActions = navigation;
export const interestActions = interests;
export const inviteActions = invites;
export const requestActions = requests;
export const searchActions = search;
export const notificationActions = notifications;
export const paymentActions = payments;
export const networkActions = network;
export const startupActions = startup;
