# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Hoops' do

	pod 'Firebase'
	pod 'Firebase/Messaging'
	pod 'React', :path => '../node_modules/react-native'
	pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    
    pod 'GoogleMaps'

end

target 'HoopsTests' do

	pod 'Firebase'
	pod 'Firebase/Messaging'

end

